[package]
name = "ml_rs" # the name of the package
version = "0.0.1"    # the current version, obeying semver
authors = ["Dmitriy Balmashnov <dmitri.balmashnov@gmail.com>"]
path = "src/main.Rs"

[dependencies]
csv="1.1"
nalgebra = "0.32.2"
serde = { version = "1", features=["derive"]}
